// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error payload carried by an [`RpcResponse::Error`].
 *
 * Wire format:
 * ```json
 * { "code": -32601, "message": "Method not found: fs.write" }
 * ```
 */
export type RpcErrorPayload = { 
/**
 * Numeric error code (see [`error_codes`]).
 */
code: number, 
/**
 * Human-readable error description. Never expose internal details
 * (stack traces, file paths) in production builds.
 */
message: string, };
