// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";
import type { RpcErrorPayload } from "./RpcErrorPayload";

/**
 * A JSON-RPC response from the Rust runtime to JavaScript.
 *
 * Exactly one of `result` or `error` is present — never both.
 *
 * Success wire format (Rust → JS):
 * ```json
 * { "id": 12, "result": { ... } }
 * ```
 *
 * Error wire format (Rust → JS):
 * ```json
 * { "id": 12, "error": { "code": -32601, "message": "Method not found: fs.write" } }
 * ```
 */
export type RpcResponse<R = JsonValue> = { id: number, result: R, } | { id: number, error: RpcErrorPayload, };
