// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

/**
 * A JSON-RPC request from JavaScript to the Rust runtime.
 *
 * Wire format (JS → Rust):
 * ```json
 * { "id": 12, "method": "fs.write", "params": { "path": "notes.json", "content": "hello" } }
 * ```
 *
 * - `id` is caller-assigned and echoed back in the response.
 * - `method` is dot-namespaced: `"<module>.<capability>"`, e.g. `"fs.write"`.
 * - `params` is a JSON object specific to the method.
 */
export type RpcRequest<P = JsonValue> = { 
/**
 * Caller-assigned request ID. Echoed back unchanged in the response.
 */
id: number, 
/**
 * Dot-namespaced method name, e.g. `"fs.write"` or `"storage.get"`.
 */
method: string, 
/**
 * Method-specific parameters as a JSON value or a typed struct.
 */
params: P, };
